import { apiError,getApiContext } from "@/lib/api-context";
import { PERMISSIONS } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { missingRequiredCustomerFields,requiredCustomerFieldsMessage } from "@/lib/customer-rules";
import { customerInput } from "@/modules/commerce/schemas";

export async function GET(request:Request){try{const {tenantId,branchId}=await getApiContext(PERMISSIONS.CUSTOMERS_VIEW_CREATE,"customers");const params=new URL(request.url).searchParams;const q=params.get("q")?.trim()??"";const inactiveDays=Number(params.get("inactiveDays")??0);const settings=await prisma.tenantSetting.findUnique({where:{tenantId}});const customers=await prisma.customer.findMany({where:{tenantId,branchId:settings?.shareCustomersAcrossBranches?undefined:branchId,deletedAt:null,OR:q?[{fullName:{contains:q,mode:"insensitive"}},{phone:{contains:q}},{document:{contains:q}}]:undefined,lastPurchaseAt:inactiveDays?{lt:new Date(Date.now()-inactiveDays*86_400_000)}:undefined},orderBy:{fullName:"asc"},take:100});return Response.json({customers})}catch(error){return apiError(error)}}

export async function POST(request:Request){try{const {tenantId,branchId,userId}=await getApiContext(PERMISSIONS.CUSTOMERS_VIEW_CREATE,"customers");const parsed=customerInput.safeParse(await request.json());if(!parsed.success)return Response.json({error:"Cliente inválido.",fields:parsed.error.flatten().fieldErrors},{status:422});const settings=await prisma.tenantSetting.findUniqueOrThrow({where:{tenantId}});const missing=missingRequiredCustomerFields(settings.requiredCustomerFields,parsed.data);if(missing.length)return Response.json({error:requiredCustomerFieldsMessage(missing),fields:Object.fromEntries(missing.map(field=>[field,["Campo obrigatório."]]))},{status:422});const customer=await prisma.$transaction(async tx=>{const created=await tx.customer.create({data:{tenantId,branchId,...parsed.data}});await tx.auditLog.create({data:{actorType:"TENANT",tenantId,branchId,userId,action:"customer.create",entity:"Customer",entityId:created.id}});return created});return Response.json({customer},{status:201})}catch(error){return apiError(error)}}
