import { apiError,getApiContext } from "@/lib/api-context";import { PERMISSIONS } from "@/lib/permissions";import { prisma } from "@/lib/prisma";
const cell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const plain=(v:unknown)=>v&&typeof v==="object"&&"toString" in v?String(v):v;
export async function GET(request:Request){try{const {tenantId,branchId,session}=await getApiContext(PERMISSIONS.REPORTS_VIEW,"reports");const p=new URL(request.url).searchParams,type=p.get("type")??"sales",format=p.get("format")??"json",from=p.get("from")?new Date(`${p.get("from")}T00:00:00`):undefined,to=p.get("to")?new Date(`${p.get("to")}T23:59:59`):undefined;const sales=await prisma.sale.findMany({where:{tenantId,branchId,status:"COMPLETED",createdAt:{gte:from,lte:to}},orderBy:{createdAt:"desc"},take:5000});const ids=sales.map(s=>s.id);let rows:Record<string,unknown>[]=[];
if(type==="sales"||type==="revenue")rows=sales.map(s=>({venda:s.id,data:s.createdAt,total:plain(s.total),desconto:plain(s.discount),status:s.status,cliente:s.customerId}));
else if(["products","categories","brands","suppliers","profit"].includes(type)){const items=await prisma.saleItem.findMany({where:{tenantId,saleId:{in:ids}}}),products=await prisma.product.findMany({where:{tenantId,id:{in:[...new Set(items.map(i=>i.productId))]}}});const groups=new Map<string,{quantidade:number;faturamento:number;custo:number}>();for(const item of items){const product=products.find(p=>p.id===item.productId);const key=type==="categories"?product?.category??"Sem categoria":type==="brands"?product?.brand??"Sem marca":type==="suppliers"?product?.supplier??"Sem fornecedor":type==="profit"?"Total":product?.name??item.description;const current=groups.get(key)??{quantidade:0,faturamento:0,custo:0};current.quantidade+=Number(item.quantity);current.faturamento+=Number(item.total);current.custo+=Number(item.quantity)*Number(product?.costPrice??0);groups.set(key,current)}rows=[...groups].map(([grupo,v])=>({grupo,...v,lucroEstimado:v.faturamento-v.custo})).sort((a,b)=>Number(b.faturamento)-Number(a.faturamento));}
else if(type==="customers")rows=(await prisma.customer.findMany({where:{tenantId,branchId,deletedAt:null},take:5000})).map(c=>({nome:c.fullName,telefone:c.phone,documento:c.document,ultimaCompra:c.lastPurchaseAt}));
else if(type==="species"){const customerIds=sales.flatMap(s=>s.customerId?[s.customerId]:[]);rows=(await prisma.pet.groupBy({by:["type"],where:{tenantId,customerId:{in:customerIds}},_count:true})).map(r=>({especie:r.type,quantidade:r._count}));}
else if(type==="stock")rows=(await prisma.stockBalance.findMany({where:{tenantId,branchId},take:5000})).map(s=>({produto:s.productId,quantidade:plain(s.quantity),custoMedio:plain(s.averageCost),atualizadoEm:s.updatedAt}));
else if(type==="cash")rows=(await prisma.cashSession.findMany({where:{tenantId,branchId,openedAt:{gte:from,lte:to}},take:5000})).map(c=>({abertura:c.openedAt,fechamento:c.closedAt,fundo:plain(c.openingAmount),esperado:plain(c.expectedAmount),contado:plain(c.countedAmount),diferenca:plain(c.difference),status:c.status}));
else if(type==="payments")rows=(await prisma.salePayment.groupBy({by:["method"],where:{tenantId,saleId:{in:ids}},_sum:{amount:true},_count:true})).map(r=>({forma:r.method,total:plain(r._sum.amount),vendas:r._count}));
else if(type==="appointments"||type==="commissions"){const appointments=await prisma.appointment.findMany({where:{tenantId,branchId,startsAt:{gte:from,lte:to}},take:5000}),professionals=await prisma.professional.findMany({where:{tenantId,branchId}});rows=appointments.map(a=>{const professional=professionals.find(pro=>pro.id===a.professionalId);return {data:a.startsAt,status:a.status,profissional:professional?.name,valor:plain(a.price),comissao:type==="commissions"?Number(a.price)*Number(professional?.commissionPercent??0)/100:undefined}});}
else if(type==="branches")rows=(await prisma.sale.groupBy({by:["branchId"],where:{tenantId,branchId:{in:session.user.branchIds},status:"COMPLETED",createdAt:{gte:from,lte:to}},_sum:{total:true},_count:true})).map(r=>({loja:r.branchId,vendas:r._count,faturamento:plain(r._sum.total)}));
else if(type==="finance")rows=(await prisma.financialEntry.findMany({where:{tenantId,branchId,dueDate:{gte:from,lte:to}},take:5000})).map(e=>({tipo:e.type,status:e.status,descricao:e.description,valor:plain(e.amount),vencimento:e.dueDate,pagamento:e.paidAt}));else return Response.json({error:"Relatório inválido."},{status:422});
if(format!=="csv")return Response.json({type,rows});const headers=rows.length?Object.keys(rows[0]):[];const csv=[headers.map(cell).join(","),...rows.map(row=>headers.map(h=>cell(row[h])).join(","))].join("\r\n");return new Response(`\ufeff${csv}`,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename=petflow-${type}.csv`}})}catch(error){return apiError(error)}}
