import { z } from "zod";

const decimal=z.union([z.string(),z.number()]).transform(value=>String(value));
export const productInput=z.object({name:z.string().trim().min(2).max(160),internalCode:z.string().trim().min(1).max(50),sku:z.string().trim().max(80).optional().nullable(),barcode:z.string().trim().max(80).optional().nullable(),category:z.string().trim().max(80).optional().nullable(),brand:z.string().trim().max(80).optional().nullable(),supplier:z.string().trim().max(120).optional().nullable(),species:z.string().trim().max(60).optional().nullable(),unit:z.string().trim().min(1).max(10).default("UN"),salePrice:decimal,costPrice:decimal,bulkSale:z.boolean().default(false),minimumStock:decimal.default("0"),location:z.string().trim().max(80).optional().nullable(),branchIds:z.array(z.string().cuid()).min(1).optional()});
export const customerInput=z.object({fullName:z.string().trim().min(2).max(160),phone:z.string().trim().min(8).max(30),address:z.string().trim().max(300).optional(),document:z.string().trim().max(30).optional(),birthDate:z.coerce.date().optional(),notes:z.string().trim().max(1000).optional()});
export const petInput=z.object({customerId:z.string().cuid(),name:z.string().trim().min(1).max(100),type:z.enum(["DOG","CAT","OTHER"]),sex:z.string().trim().max(20).optional(),breed:z.string().trim().max(80).optional(),birthDate:z.coerce.date().optional(),notes:z.string().trim().max(1000).optional()});
export const stockMovementInput=z.object({productId:z.string().cuid(),type:z.enum(["ENTRY","EXIT","ADJUSTMENT","INVENTORY","TRANSFER"]),quantity:decimal,unitCost:decimal.optional(),reason:z.string().trim().min(3).max(300),destinationBranchId:z.string().cuid().optional()});
export const saleInput=z.object({idempotencyKey:z.string().min(8).max(100),customerId:z.string().cuid().optional().nullable(),discount:decimal.default("0"),items:z.array(z.object({productId:z.string().cuid(),quantity:decimal.optional(),chargedAmount:decimal.optional(),discount:decimal.default("0")})).min(1),payments:z.array(z.object({method:z.string().trim().min(2).max(30),amount:decimal})).min(1)});
export const financialEntryInput=z.object({type:z.enum(["PAYABLE","RECEIVABLE"]),categoryId:z.preprocess(value=>value===""?undefined:value,z.string().cuid().optional()),description:z.string().trim().min(2).max(200),amount:decimal,dueDate:z.coerce.date(),paymentMethod:z.string().trim().max(30).optional(),originType:z.string().trim().max(40).optional(),originId:z.string().max(100).optional()});
export const appointmentInput=z.object({professionalId:z.string().cuid(),serviceId:z.string().cuid().optional(),customerId:z.string().cuid().optional(),petId:z.string().cuid().optional(),startsAt:z.coerce.date(),notes:z.string().trim().max(1000).optional()});
