import { apiError,getApiContext } from "@/lib/api-context";
import { money } from "@/lib/money";
import { PERMISSIONS } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { financialEntryInput } from "@/modules/commerce/schemas";

const patchSchema=financialEntryInput.partial();
export async function PATCH(request:Request,context:RouteContext<"/api/finance/[id]">){try{const {tenantId,branchId,userId}=await getApiContext(PERMISSIONS.FINANCE_VIEW,"finance");const {id}=await context.params;const parsed=patchSchema.safeParse(await request.json());if(!parsed.success)return Response.json({error:"Alteração inválida."},{status:422});const current=await prisma.financialEntry.findFirst({where:{id,tenantId,branchId,status:"OPEN"}});if(!current)return Response.json({error:"Lançamento aberto não encontrado."},{status:404});if(parsed.data.categoryId&&!await prisma.financialCategory.findFirst({where:{id:parsed.data.categoryId,tenantId}}))return Response.json({error:"Categoria inválida."},{status:403});const data={...parsed.data,amount:parsed.data.amount?money(parsed.data.amount):undefined};const entry=await prisma.$transaction(async tx=>{const updated=await tx.financialEntry.update({where:{id},data});await tx.auditLog.create({data:{actorType:"TENANT",tenantId,branchId,userId,action:"finance.entry.update",entity:"FinancialEntry",entityId:id,metadata:{before:current,after:updated}}});return updated});return Response.json({entry})}catch(error){return apiError(error)}}
export async function DELETE(request:Request,context:RouteContext<"/api/finance/[id]">){try{const {tenantId,branchId,userId}=await getApiContext(PERMISSIONS.FINANCE_VIEW,"finance");const {id}=await context.params;const body=await request.json().catch(()=>({}));const reason=typeof body.reason==="string"?body.reason.trim():"";if(reason.length<3)return Response.json({error:"Informe o motivo do cancelamento."},{status:422});if(!await prisma.financialEntry.findFirst({where:{id,tenantId,branchId,status:"OPEN"}}))return Response.json({error:"Lançamento aberto não encontrado."},{status:404});const entry=await prisma.$transaction(async tx=>{const updated=await tx.financialEntry.update({where:{id},data:{status:"CANCELLED"}});await tx.auditLog.create({data:{actorType:"TENANT",tenantId,branchId,userId,action:"finance.entry.cancel",entity:"FinancialEntry",entityId:id,reason}});return updated});return Response.json({entry})}catch(error){return apiError(error)}}
