import Link from "next/link";
import { PawPrint,Sparkles } from "lucide-react";
import { SessionControls } from "@/components/session-controls";
import { SidebarNav,type NavIconKey } from "@/components/sidebar-nav";
import type { ModuleKey } from "@/lib/modules";
type Props={platform?:boolean;userName:string;tenantName?:string;branches?:Array<{id:string;name:string}>;activeBranchId?:string;enabledModules?:string[];children:React.ReactNode};
const tenantLinks:Array<[string,string,NavIconKey,ModuleKey?]>=[["/app","Visão geral","LayoutDashboard","dashboard"],["/app/produtos","Produtos","PackageSearch","products"],["/app/estoque","Estoque","Warehouse","stock"],["/app/clientes","Clientes","Users","customers"],["/app/vendas","Vendas","ShoppingCart","sales"],["/app/caixa","Caixa","ReceiptText","cash"],["/app/financeiro","Financeiro","CircleDollarSign","finance"],["/app/banho-e-tosa","Banho e tosa","CalendarDays","grooming"],["/app/relatorios","Relatórios","BarChart3","reports"],["/app/fiscal","Fiscal","ReceiptText","fiscal"],["/app/equipe","Equipe e acessos","Users"],["/app/auditoria","Auditoria","ShieldCheck"],["/app#configuracoes","Configurações","Settings"],["/app#lojas","Lojas","Store"]];
const platformLinks:Array<[string,string,NavIconKey]>=[["/platform","Visão geral","LayoutDashboard"],["/platform#empresas","Empresas","Building2"],["/platform#planos","Planos","BarChart3"],["/platform#auditoria","Auditoria","ShieldCheck"]];
export function AppShell({platform=false,userName,tenantName,branches,activeBranchId,enabledModules=[],children}:Props){const links=platform?platformLinks:tenantLinks.filter(([, , ,module])=>!module||enabledModules.includes(module));return <div className={platform?"shell shell--platform":"shell"}><aside className="sidebar"><Link className="brand" href={platform?"/platform":"/app"}><span className="brand-mark"><PawPrint size={21}/></span><span>PetFlow</span></Link>{platform&&<span className="platform-tag"><Sparkles size={12}/>Administração SaaS</span>}<SidebarNav links={links}/><div className="sidebar-foot">{platform?"Painel da plataforma":tenantName}<br/>Ambiente protegido</div></aside><div className="main"><header className="topbar"><div className="topbar-title">{platform?"Administração SaaS":tenantName}</div><div className="user-chip"><span>{userName}</span><span className="avatar">{userName.slice(0,1).toUpperCase()}</span><SessionControls branches={branches} activeBranchId={activeBranchId}/></div></header><main className="content">{children}</main></div></div>}
