"use client";
import { useState } from "react";
import { Building2, Plus } from "lucide-react";

export function CreateTenantForm({ plans }: { plans: Array<{ id: string; name: string }> }) {
  const [message,setMessage]=useState(""); const [pending,setPending]=useState(false);
  async function submit(formData:FormData){setPending(true);setMessage("");const body=Object.fromEntries(formData);const response=await fetch("/api/platform/tenants",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setMessage(response.ok?"Empresa criada com matriz e administrador.":result.error);setPending(false);if(response.ok)location.reload()}
  return <form action={submit} className="section-card card"><div className="section-title"><div><span className="eyebrow">Onboarding seguro</span><h2>Nova empresa</h2></div><span className="quick-icon"><Building2 size={18}/></span></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><div className="field"><label>Nome</label><input className="input" name="name" required/></div><div className="field"><label>Identificador</label><input className="input" name="slug" placeholder="pet-central" required/></div><div className="field"><label>Documento</label><input className="input" name="document"/></div><div className="field"><label>Plano</label><select className="input" name="planId" required>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></div><div className="field"><label>Administrador</label><input className="input" name="adminName" required/></div><div className="field"><label>Usuário</label><input className="input" name="adminUsername" required/></div><div className="field" style={{gridColumn:"1 / -1"}}><label>Senha inicial</label><input className="input" name="adminPassword" type="password" minLength={10} required/></div></div>{message?<p className={message.startsWith("Empresa criada")?"pill":"error"} style={{marginTop:14}}>{message}</p>:null}<button className="button button-primary" disabled={pending} style={{marginTop:16,width:"100%"}}><Plus size={17}/>{pending?"Criando…":"Criar empresa"}</button></form>
}
