"use client";

import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useEffect,useMemo,useRef,useState } from "react";
import { Minus,Plus,Search,ShoppingCart,Trash2 } from "lucide-react";

type Product={id:string;name:string;internalCode:string;sku:string|null;barcode:string|null;salePrice:string;bulkSale:boolean;unit:string};
type Customer={id:string;fullName:string;phone:string};
type Sale={id:string;total:string;status:string;createdAt:string};
type CartLine={product:Product;quantity:number;chargedAmount:string;discount:string};
type Payment={id:string;method:string;amount:string};
type Settings={acceptedPaymentMethods:string[];customerRequiredOnSale:boolean};

async function json(url:string,init?:RequestInit){const response=await fetch(url,init);const data=await response.json();if(!response.ok)throw new Error(data.error??"Falha na operação.");return data}
const money=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;

export function SalesWorkspace(){
  const client=useQueryClient();
  const searchRef=useRef<HTMLInputElement>(null);
  const idempotencyKey=useRef(crypto.randomUUID());
  const [search,setSearch]=useState("");
  const [debounced,setDebounced]=useState("");
  const [cart,setCart]=useState<CartLine[]>([]);
  const [message,setMessage]=useState("");
  const [customerId,setCustomerId]=useState("");
  const [payments,setPayments]=useState<Payment[]>([{id:crypto.randomUUID(),method:"",amount:""}]);
  const [generalDiscount,setGeneralDiscount]=useState("0");
  useEffect(()=>{const timer=setTimeout(()=>setDebounced(search),300);return()=>clearTimeout(timer)},[search]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==="F2"){event.preventDefault();searchRef.current?.focus()}if(event.key==="F4"){event.preventDefault();document.getElementById("finish-sale")?.click()}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
  const products=useQuery<{products:Product[]}>({queryKey:["products-sale",debounced],queryFn:()=>json(`/api/products?q=${encodeURIComponent(debounced)}`)});
  const customers=useQuery<{customers:Customer[]}>({queryKey:["customers-sale"],queryFn:()=>json("/api/customers")});
  const sales=useQuery<{sales:Sale[]}>({queryKey:["sales"],queryFn:()=>json("/api/sales")});
  const settings=useQuery<{settings:Settings}>({queryKey:["settings-sale"],queryFn:()=>json("/api/settings")});
  const methods=settings.data?.settings.acceptedPaymentMethods?.length?settings.data.settings.acceptedPaymentMethods:["PIX","DINHEIRO","DEBITO","CREDITO"];
  const subtotal=useMemo(()=>cart.reduce((sum,line)=>sum+(line.product.bulkSale&&line.chargedAmount?Number(line.chargedAmount):Number(line.product.salePrice)*line.quantity)-Number(line.discount||0),0),[cart]);
  const total=money(Math.max(0,subtotal-Number(generalDiscount||0)));
  const paymentTotal=money(payments.reduce((sum,payment)=>sum+Number(payment.amount||0),0));
  const cashAmount=money(payments.filter(payment=>payment.method==="DINHEIRO").reduce((sum,payment)=>sum+Number(payment.amount||0),0));
  const nonCashAmount=money(paymentTotal-cashAmount);
  const cashDue=money(Math.max(0,total-nonCashAmount));
  const change=money(Math.max(0,cashAmount-cashDue));
  const amountApplied=money(paymentTotal-change);
  const remaining=money(Math.max(0,total-amountApplied));
  const validPayments=payments.every(payment=>payment.method&&Number(payment.amount)>0)&&Math.abs(amountApplied-total)<0.001;
  function paymentsForApi(){let pendingChange=change;return payments.map(payment=>{let amount=Number(payment.amount);if(payment.method==="DINHEIRO"&&pendingChange>0){const deduction=Math.min(amount,pendingChange);amount=money(amount-deduction);pendingChange=money(pendingChange-deduction)}return {method:payment.method,amount:amount.toFixed(2)}}).filter(payment=>Number(payment.amount)>0)}
  const saleMutation=useMutation({mutationFn:()=>json("/api/sales",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idempotencyKey:idempotencyKey.current,customerId:customerId||null,discount:generalDiscount,items:cart.map(line=>({productId:line.product.id,quantity:line.product.bulkSale&&line.chargedAmount?undefined:String(line.quantity),chargedAmount:line.product.bulkSale&&line.chargedAmount?line.chargedAmount:undefined,discount:line.discount||"0"})),payments:paymentsForApi()})}),onSuccess:()=>{setCart([]);setPayments([{id:crypto.randomUUID(),method:"",amount:""}]);setGeneralDiscount("0");idempotencyKey.current=crypto.randomUUID();setMessage(`Venda concluída.${change>0?` Troco: R$ ${change.toFixed(2)}.`:""}`);client.invalidateQueries({queryKey:["sales"]});client.invalidateQueries({queryKey:["stock"]});client.invalidateQueries({queryKey:["cash-details"]})},onError:(error)=>setMessage(error.message)});
  function add(product:Product){setCart(lines=>{const current=lines.find(line=>line.product.id===product.id);return current?lines.map(line=>line.product.id===product.id?{...line,quantity:line.quantity+1}:line):[...lines,{product,quantity:1,chargedAmount:"",discount:"0"}]})}
  function updatePayment(id:string,patch:Partial<Payment>){setPayments(rows=>rows.map(row=>row.id===id?{...row,...patch}:row))}
  async function cancel(id:string){const reason=prompt("Informe o motivo do cancelamento:");if(!reason||reason.trim().length<5)return;if(!confirm("Cancelar esta venda e devolver os itens ao estoque?"))return;try{await json(`/api/sales/${id}/cancel`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({reason})});setMessage("Venda cancelada e estoque reposto.");client.invalidateQueries({queryKey:["sales"]})}catch(error){setMessage(error instanceof Error?error.message:"Falha ao cancelar.")}}
  return <>
    <header className="page-head"><div><span className="eyebrow">PDV · F2 busca · F4 finalizar</span><h1 className="display">Venda rápida</h1><p>Busque, monte o carrinho e finalize sem sair desta tela.</p></div><span className="pill"><ShoppingCart size={15}/>{cart.length} itens</span></header>
    <div className="pdv-grid"><section className="card section-card"><div className="search-box"><Search size={18}/><input ref={searchRef} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, código, SKU ou código de barras" aria-label="Buscar produto"/></div><div className="product-results">{products.isFetching?<span className="muted">Atualizando lista…</span>:null}{(products.data?.products??[]).map(product=><button className="product-result" key={product.id} onClick={()=>add(product)}><span><strong>{product.name}</strong><small>{product.internalCode} · {product.unit}{product.bulkSale?" · granel":""}</small></span><b>R$ {Number(product.salePrice).toFixed(2)}</b><Plus size={17}/></button>)}</div><div className="section-title" style={{marginTop:22}}><h2>Carrinho</h2></div>{cart.length?<div className="cart-list">{cart.map(line=><article className="cart-line" key={line.product.id}><div><strong>{line.product.name}</strong><small>R$ {Number(line.product.salePrice).toFixed(2)} / {line.product.unit}</small></div>{line.product.bulkSale?<><label>Kg<input type="number" min="0.001" step="0.001" value={line.quantity} onChange={e=>setCart(rows=>rows.map(row=>row.product.id===line.product.id?{...row,quantity:Number(e.target.value)}:row))}/></label><label>Ou valor R$<input type="number" min="0.01" step="0.01" value={line.chargedAmount} onChange={e=>setCart(rows=>rows.map(row=>row.product.id===line.product.id?{...row,chargedAmount:e.target.value}:row))}/></label></>:<div className="qty"><button onClick={()=>setCart(rows=>rows.map(row=>row.product.id===line.product.id?{...row,quantity:Math.max(1,row.quantity-1)}:row))}><Minus size={15}/></button><b>{line.quantity}</b><button onClick={()=>setCart(rows=>rows.map(row=>row.product.id===line.product.id?{...row,quantity:row.quantity+1}:row))}><Plus size={15}/></button></div>}<label>Desconto<input type="number" min="0" step="0.01" value={line.discount} onChange={e=>setCart(rows=>rows.map(row=>row.product.id===line.product.id?{...row,discount:e.target.value}:row))}/></label><button className="icon-button danger" aria-label={`Remover ${line.product.name}`} onClick={()=>setCart(rows=>rows.filter(row=>row.product.id!==line.product.id))}><Trash2 size={17}/></button></article>)}</div>:<div className="empty-state">Busque um produto para começar.</div>}</section>
      <aside className="card section-card checkout"><div className="section-title"><h2>Pagamento</h2></div><div className="field"><label>Cliente{settings.data?.settings.customerRequiredOnSale?" *":""}</label><select className="input" value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Consumidor não identificado</option>{(customers.data?.customers??[]).map(c=><option key={c.id} value={c.id}>{c.fullName} · {c.phone}</option>)}</select></div><div className="field"><label>Desconto geral</label><input className="input" type="number" min="0" step="0.01" value={generalDiscount} onChange={e=>setGeneralDiscount(e.target.value)}/></div><div className="payment-list">{payments.map((payment,index)=><div className="payment-row" key={payment.id}><select className="input" aria-label={`Forma de pagamento ${index+1}`} value={payment.method} onChange={e=>updatePayment(payment.id,{method:e.target.value})}><option value="">Selecione…</option>{methods.map(item=><option key={item} value={item}>{item}</option>)}</select><input className="input" aria-label={`Valor do pagamento ${index+1}`} type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>updatePayment(payment.id,{amount:e.target.value})} placeholder="0,00"/><button className="icon-button danger" aria-label="Remover pagamento" disabled={payments.length===1} onClick={()=>setPayments(rows=>rows.filter(row=>row.id!==payment.id))}><Trash2 size={16}/></button></div>)}</div><button className="button button-ghost" onClick={()=>setPayments(rows=>[...rows,{id:crypto.randomUUID(),method:"",amount:remaining?remaining.toFixed(2):""}])}>+ Dividir pagamento</button><div className="checkout-summary"><span>Pagamentos <b>R$ {paymentTotal.toFixed(2)}</b></span>{remaining>0?<span>Falta <b>R$ {remaining.toFixed(2)}</b></span>:null}{change>0?<span className="success">Troco <b>R$ {change.toFixed(2)}</b></span>:null}</div><div className="checkout-total"><span>Total</span><strong>R$ {total.toFixed(2)}</strong></div>{message?<p className={message.includes("concluída")||message.includes("cancelada")?"success":"error"}>{message}</p>:null}<button id="finish-sale" className="button button-primary" disabled={!cart.length||!validPayments||(settings.data?.settings.customerRequiredOnSale&&!customerId)||saleMutation.isPending} onClick={()=>saleMutation.mutate()}>{saleMutation.isPending?"Finalizando…":"Finalizar venda"}</button></aside></div>
    <section className="card section-card" style={{marginTop:18}}><div className="section-title"><h2>Histórico de vendas</h2></div><div className="record-list">{(sales.data?.sales??[]).map(s=><article className="record" key={s.id}><span><small>Venda</small><strong>{s.id.slice(-8)}</strong></span><span><small>Total</small><strong>R$ {Number(s.total).toFixed(2)}</strong></span><span><small>Status</small><strong>{s.status}</strong></span><span><small>Data</small><strong>{new Date(s.createdAt).toLocaleString("pt-BR")}</strong></span>{s.status==="COMPLETED"?<button className="button button-ghost" onClick={()=>cancel(s.id)}>Cancelar</button>:null}</article>)}</div></section>
  </>
}
