"use client";
import { useState } from "react";
import { PERMISSIONS } from "@/lib/permissions";

const labels:Record<string,string>={"sales:view-create":"Cadastrar vendas","sales:view-cancel":"Cancelar vendas","cash:view-operate":"Operar caixa","stock:view-move":"Movimentar estoque","products:view-create":"Cadastrar produtos","customers:view-create":"Cadastrar clientes","reports:view":"Visualizar relatórios","finance:view":"Visualizar financeiro","grooming:manage":"Gerenciar banho e tosa","users:manage":"Administrar usuários","settings:manage":"Administrar configurações"};

export function CreateRoleForm(){const [message,setMessage]=useState("");async function submit(formData:FormData){const response=await fetch("/api/roles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:formData.get("name"),description:formData.get("description"),permissionKeys:formData.getAll("permissionKeys")})});const result=await response.json();setMessage(response.ok?"Cargo criado com permissões exatas.":result.error);if(response.ok)location.reload()}return <form action={submit} className="section-card card"><div className="section-title"><div><span className="eyebrow">RBAC</span><h2>Novo cargo</h2></div></div><div className="login-form"><div className="field"><label>Nome</label><input className="input" name="name" required/></div><div className="field"><label>Descrição</label><input className="input" name="description"/></div><div className="field"><label>Permissões</label><div style={{display:"grid",gap:8}}>{Object.values(PERMISSIONS).map(key=><label key={key} style={{fontWeight:500}}><input type="checkbox" name="permissionKeys" value={key}/> {labels[key]}</label>)}</div></div><button className="button button-ghost">Criar cargo</button>{message?<span className="pill">{message}</span>:null}</div></form>}

export function CreateBranchForm(){const [message,setMessage]=useState("");async function submit(formData:FormData){const response=await fetch("/api/branches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(formData))});const result=await response.json();setMessage(response.ok?"Loja criada dentro do limite do plano.":result.error);if(response.ok)location.reload()}return <form action={submit} className="section-card card"><div className="section-title"><div><span className="eyebrow">Estrutura</span><h2>Nova loja</h2></div></div><div className="login-form"><div className="field"><label>Nome</label><input className="input" name="name" required/></div><div className="field"><label>Código</label><input className="input" name="code" placeholder="LOJA02" required/></div><button className="button button-ghost">Criar loja</button>{message?<span className="pill">{message}</span>:null}</div></form>}

type Settings={brandName:string|null;primaryColor:string;allowNegativeStock:boolean;shareProductsAcrossBranches:boolean;shareCustomersAcrossBranches:boolean;bulkSaleEnabled:boolean;professionalCommissionEnabled:boolean};
export function TenantSettingsForm({settings}:{settings:Settings}){const [message,setMessage]=useState("");async function submit(formData:FormData){const body={brandName:formData.get("brandName"),primaryColor:formData.get("primaryColor"),allowNegativeStock:formData.has("allowNegativeStock"),shareProductsAcrossBranches:formData.has("shareProductsAcrossBranches"),shareCustomersAcrossBranches:formData.has("shareCustomersAcrossBranches"),bulkSaleEnabled:formData.has("bulkSaleEnabled"),professionalCommissionEnabled:formData.has("professionalCommissionEnabled")};const response=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setMessage(response.ok?"Configurações salvas e auditadas.":result.error)}return <form action={submit} className="section-card card"><div className="section-title"><div><span className="eyebrow">Regras da empresa</span><h2>Configurações</h2></div></div><div className="login-form"><div className="field"><label>Nome da marca</label><input className="input" name="brandName" defaultValue={settings.brandName??""}/></div><div className="field"><label>Cor principal</label><input className="input" name="primaryColor" type="color" defaultValue={settings.primaryColor}/></div>{[["allowNegativeStock","Permitir estoque negativo",settings.allowNegativeStock],["shareProductsAcrossBranches","Compartilhar produtos",settings.shareProductsAcrossBranches],["shareCustomersAcrossBranches","Compartilhar clientes",settings.shareCustomersAcrossBranches],["bulkSaleEnabled","Venda a granel",settings.bulkSaleEnabled],["professionalCommissionEnabled","Comissão de profissionais",settings.professionalCommissionEnabled]].map(([name,label,checked])=><label key={String(name)}><input type="checkbox" name={String(name)} defaultChecked={Boolean(checked)}/> {label}</label>)}<button className="button button-ghost">Salvar configurações</button>{message?<span className="pill">{message}</span>:null}</div></form>}
