import { hash } from "bcryptjs";
import { getServerSession } from "next-auth";
import { NextResponse } from "next/server";
import { z } from "zod";
import { authOptions } from "@/lib/auth";
import { PERMISSIONS,hasPermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";

const updateSchema=z.object({name:z.string().trim().min(2).max(120).optional(),roleId:z.string().cuid().optional(),branchIds:z.array(z.string().cuid()).min(1).optional(),status:z.enum(["ACTIVE","INACTIVE","LOCKED"]).optional()});
const passwordSchema=z.object({password:z.string().min(10).max(128)});
async function authorize(){const session=await getServerSession(authOptions);if(!session?.user.tenantId||!hasPermission(session.user.permissions,PERMISSIONS.USERS_MANAGE))return null;return session}

export async function PATCH(request:Request,context:RouteContext<"/api/employees/[id]">){const session=await authorize();if(!session)return NextResponse.json({error:"Sem permissão."},{status:403});const parsed=updateSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Dados inválidos."},{status:422});const {id}=await context.params;if(id===session.user.id&&parsed.data.status&&parsed.data.status!=="ACTIVE")return NextResponse.json({error:"Você não pode desativar o próprio usuário."},{status:409});const tenantId=session.user.tenantId!;const current=await prisma.user.findFirst({where:{id,tenantId,deletedAt:null}});if(!current)return NextResponse.json({error:"Usuário não encontrado."},{status:404});if(parsed.data.roleId&&!await prisma.role.findFirst({where:{id:parsed.data.roleId,tenantId}}))return NextResponse.json({error:"Cargo fora da empresa."},{status:403});if(parsed.data.branchIds){const count=await prisma.branch.count({where:{id:{in:parsed.data.branchIds},tenantId,active:true,deletedAt:null}});if(count!==parsed.data.branchIds.length)return NextResponse.json({error:"Uma das lojas é inválida."},{status:403})}const user=await prisma.$transaction(async tx=>{if(parsed.data.branchIds){await tx.userBranch.deleteMany({where:{tenantId,userId:id}});await tx.userBranch.createMany({data:parsed.data.branchIds.map(branchId=>({tenantId,userId:id,branchId}))})}const updated=await tx.user.update({where:{id},data:{name:parsed.data.name,roleId:parsed.data.roleId,status:parsed.data.status,lockedUntil:parsed.data.status==="ACTIVE"?null:undefined,failedAttempts:parsed.data.status==="ACTIVE"?0:undefined},select:{id:true,name:true,username:true,status:true}});await tx.auditLog.create({data:{actorType:"TENANT",tenantId,userId:session.user.id,action:"user.update",entity:"User",entityId:id}});return updated});return NextResponse.json({user})}

export async function PUT(request:Request,context:RouteContext<"/api/employees/[id]">){const session=await authorize();if(!session)return NextResponse.json({error:"Sem permissão."},{status:403});const parsed=passwordSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Senha inválida."},{status:422});const {id}=await context.params;const tenantId=session.user.tenantId!;if(!await prisma.user.findFirst({where:{id,tenantId,deletedAt:null}}))return NextResponse.json({error:"Usuário não encontrado."},{status:404});await prisma.$transaction([prisma.user.update({where:{id},data:{passwordHash:await hash(parsed.data.password,12),failedAttempts:0,lockedUntil:null,status:"ACTIVE"}}),prisma.auditLog.create({data:{actorType:"TENANT",tenantId,userId:session.user.id,action:"user.password.reset",entity:"User",entityId:id}})]);return NextResponse.json({ok:true})}
