import { apiError,getApiContext } from "@/lib/api-context";
import { PERMISSIONS } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { customerInput } from "@/modules/commerce/schemas";
import { missingRequiredCustomerFields,requiredCustomerFieldsMessage } from "@/lib/customer-rules";
const schema=customerInput.partial();
export async function GET(_:Request,context:RouteContext<"/api/customers/[id]">){try{const {tenantId}=await getApiContext(PERMISSIONS.CUSTOMERS_VIEW_CREATE,"customers");const {id}=await context.params;const customer=await prisma.customer.findFirst({where:{id,tenantId,deletedAt:null}});if(!customer)return Response.json({error:"Cliente não encontrado."},{status:404});const [pets,sales,appointments]=await Promise.all([prisma.pet.findMany({where:{tenantId,customerId:id,deletedAt:null}}),prisma.sale.findMany({where:{tenantId,customerId:id},orderBy:{createdAt:"desc"},take:30}),prisma.appointment.findMany({where:{tenantId,customerId:id},orderBy:{startsAt:"desc"},take:30})]);return Response.json({customer,pets,sales,appointments})}catch(error){return apiError(error)}}
export async function PATCH(request:Request,context:RouteContext<"/api/customers/[id]">){try{const {tenantId,branchId,userId}=await getApiContext(PERMISSIONS.CUSTOMERS_VIEW_CREATE,"customers");const {id}=await context.params;const parsed=schema.safeParse(await request.json());if(!parsed.success)return Response.json({error:"Cliente inválido."},{status:422});const [existing,settings]=await Promise.all([prisma.customer.findFirst({where:{id,tenantId,deletedAt:null}}),prisma.tenantSetting.findUniqueOrThrow({where:{tenantId}})]);if(!existing)return Response.json({error:"Cliente não encontrado."},{status:404});const missing=missingRequiredCustomerFields(settings.requiredCustomerFields,{...existing,...parsed.data});if(missing.length)return Response.json({error:requiredCustomerFieldsMessage(missing)},{status:422});const customer=await prisma.$transaction(async tx=>{const updated=await tx.customer.update({where:{id},data:parsed.data});await tx.auditLog.create({data:{actorType:"TENANT",tenantId,branchId,userId,action:"customer.update",entity:"Customer",entityId:id}});return updated});return Response.json({customer})}catch(error){return apiError(error)}}
export async function DELETE(_:Request,context:RouteContext<"/api/customers/[id]">){try{const {tenantId,branchId,userId}=await getApiContext(PERMISSIONS.CUSTOMERS_VIEW_CREATE,"customers");const {id}=await context.params;if(!await prisma.customer.findFirst({where:{id,tenantId,deletedAt:null}}))return Response.json({error:"Cliente não encontrado."},{status:404});await prisma.$transaction([prisma.customer.update({where:{id},data:{deletedAt:new Date()}}),prisma.pet.updateMany({where:{tenantId,customerId:id},data:{deletedAt:new Date()}}),prisma.auditLog.create({data:{actorType:"TENANT",tenantId,branchId,userId,action:"customer.delete",entity:"Customer",entityId:id}})]);return Response.json({ok:true})}catch(error){return apiError(error)}}
